import logos from './brand-logos.json';

// Generated by scripts/fetch-brand-logos.mjs
const LOGOS = logos as Record<string, { file: string; source: string }>;

const base = import.meta.env.BASE_URL.replace(/\/$/, '');

export function getBrandLogoUrl(slug: string | null | undefined): string | null {
  const entry = slug ? LOGOS[slug] : undefined;
  return entry ? `${base}/${entry.file}` : null;
}

// Stable 32-bit hash so every brand/model gets the same accent and illustration variant on each build.
export function hashString(value: string): number {
  let h = 5381;
  for (let i = 0; i < value.length; i++) h = ((h << 5) + h + value.charCodeAt(i)) >>> 0;
  return h;
}

export function brandAccent(slug: string): string {
  // Dark enough that white initials stay above 4.5:1 contrast for every hue, including yellows and greens.
  return `hsl(${hashString(slug) % 360} 60% 28%)`;
}
