import photos from './model-images.json';

// Generated by scripts/fetch-model-images.mjs
const PHOTOS = photos as Record<string, { file: string; image: string; page: string }>;

const base = import.meta.env.BASE_URL.replace(/\/$/, '');

export function getModelPhoto(slug: string | null | undefined) {
  const entry = slug ? PHOTOS[slug] : undefined;
  if (!entry) return null;
  let sourceHost = '';
  try { sourceHost = new URL(entry.page).hostname.replace(/^www\./, ''); } catch {}
  return { url: `${base}/${entry.file}`, sourcePage: entry.page, sourceHost };
}
